Session1
Hyperbolic4183/YumemiWeather pull request #1
Opened 2021-04-30 03:02 UTC by Hyperbolic4183

## 行なったこと
画面レイアウトを構成した

![Simulator Screen Shot - iPhone 8 - 2021-04-26 at 05 18 11](https://user-images.githubusercontent.com/60565914/116008369-22b75700-a64f-11eb-81bd-d8fb8c30a446.png)

## 懸念点
- UI部品の場所・大きさをNSLayoutConstraintではなくCGRectで全て行なっていること
- WeatherViewController.swift　の中で変数名とクラス名が同じになっていること

## 工夫したところ
- ボタンの判定を見た目より大きくしたところ
- ViewとControllerで責務を分けたところ

## 聞きたいこと
- NSLayoutConstraintとCGRectの使い分けはどのようにするのが良いか。

2021-04-30 06:19 UTC, rizumita commented
@Hyperbolic4183 
[Session1](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/AutoLayout.md)はAutoLayoutで行うものだと思うのですが、何か指示がありましたか？

2021-04-30 07:17 UTC, Hyperbolic4183 commented
> @Hyperbolic4183
> [Session1](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/AutoLayout.md)はAutoLayoutで行うものだと思うのですが、何か指示がありましたか？

特に指示はありませんでした。
AutoLayoutがUI部品の場所の指定を行うことそのもので、CGFrameはその方法の一つだと思っていました。

2021-04-30 07:29 UTC, rizumita commented
@Hyperbolic4183 
frameを直接変更するのはManual Layout、AutoLayoutは制約によるレイアウトで、別物です。
ということでおそらくこのセッションはAutoLayoutを学ぶためのものと思われるので、AutoLayoutで書き換えてみてください。

2021-04-30 07:34 UTC, Hyperbolic4183 commented
> @Hyperbolic4183
> frameを直接変更するのはManual Layout、AutoLayoutは制約によるレイアウトで、別物です。
> ということでおそらくこのセッションはAutoLayoutを学ぶためのものと思われるので、AutoLayoutで書き換えてみてください。

わかりました！

2021-05-07 01:32 UTC, Hyperbolic4183 commented
AutoLayoutで作り直しました。
レビューよろしくお願いします！

2021-05-07 06:39 UTC, rizumita requested changes

2021-05-07 06:39 UTC, rizumita commented on Yumemi-ios-training/WeatherView.swift
> +    private func setupstackViewForImageViewAndLabels() {
setupStack…とStackの頭文字は大文字にすると良いですね。一つ下のメソッドも同様ですね。

2021-05-07 06:39 UTC, rizumita commented on Yumemi-ios-training/WeatherView.swift
> +        addSubview(stackViewForImageViewAndLabels)
行数が長く似たような処理が続くので、各ビューごとに先頭にコメントを記述してそのブロックがどのビューを設定しているか分かるようにすると、内容が分かりやすくなります。

2021-05-07 07:57 UTC, yumemi-kterada commented on Yumemi-ios-training/WeatherViewController.swift
> +        view = weatherView
[IMO] 実装がシンプルで良いと思いますが、
自分ならaddSubview() + Constraintを使います。

2021-05-07 07:59 UTC, yumemi-kterada commented on Yumemi-ios-training/WeatherViewController.swift
> +    override func loadView() {
super.loadView()
ここは必要なかったでしたっけ。
記憶が曖昧なのですが、一応確認です。

2021-05-07 08:06 UTC, Hyperbolic4183 commented on Yumemi-ios-training/WeatherViewController.swift
> +        view = weatherView
@yumemi-kterada
```
view.addSubView(weatherView)
NSLayoutConstraint.activate([
    weatherView.centerXAnchor.constraint(equalTo: view.centerXAnchor),
    weatherView.centerYAnchor.constraint(equalTo: view.centerYAnchor),
    weatherView.widthYAnchor.constraint(equalTo: view.widthAnchor),
    weatherView.heightYAnchor.constraint(equalTo: view.heightAnchor),
])
])
])
```

というイメージでしょうか？

2021-05-07 08:20 UTC, Hyperbolic4183 commented on Yumemi-ios-training/WeatherViewController.swift
> +    override func loadView() {
@yumemi-kterada
意識してなかったです。
[loadView](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621454-loadview)にsuperの呼び出しについて言及されてる部分があるのでもう少し調べます。

2021-05-07 08:34 UTC, merged

2021-05-07 08:43 UTC, yumemi-kterada commented on Yumemi-ios-training/WeatherViewController.swift
> +        view = weatherView
そうですね。実際にはConstraintの処理は定型なので自分の場合は、（別定義で）１行で書けるようにしています。
`view = weatherView` は
親のViewControllerのルートview（言い方適当です）のインスタンスを置き換える処理になるので、自分は避けると思います、程度です。

2021-05-07 08:46 UTC, yumemi-kterada commented
approveされてからmergeの方が良いと思います。