Session8
Hyperbolic4183/YumemiWeather pull request #13
Opened 2021-06-18 05:36 UTC by Hyperbolic4183

2021-06-18 15:31 UTC, ykws reviewed
テストパスすることができていて素晴らしいと思います！

いくつか細かい部分でコメントしましたので確認をお願いします。

2021-06-18 15:31 UTC, ykws commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +    var weatherModel: Testable
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

本実装のコードがテストに依存する形になるので避けたいかなと思いました。
テスト対象の Protocol を用意して、本実装用と、テスト実装用の Stub を用意することでテストできる方が
本実装がテストことを知らないで済むので嬉しいです。

2021-06-18 15:31 UTC, ykws commented on Yumemi-ios-training/Model/Testable.swift
> +import Foundation
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

`import` と `protocol` の間は空行が欲しいです。
フォーマットに関しては [SwiftLint](https://github.com/realm/SwiftLint) を導入してみても良いかもです。

[Swiftの静的解析ツール「SwiftLint」のセットアップ方法](https://qiita.com/uhooi/items/bf888b53b4b8210108aa)

2021-06-18 15:31 UTC, ykws commented on Yumemi-ios-training/Model/Testable.swift
> +protocol Testable {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

命名の問題だけのようですね。
`protocol` を抽出して本実装とテスト実装というパターンができているので良いと思います。

Fetcher の protocol なので Fetchable とか 🤔 （造語っぽくてスペルチェックで引っかかるかも）

2021-06-18 15:31 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    func test_天気予報がcloudyだったときに画面に晴れ画像が表示される() {
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

```suggestion
    func test_天気予報がcloudyだったときに画面に曇り画像が表示される() {
```

2021-06-18 15:31 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    func test_天気予報がrainyだったときに画面に晴れ画像が表示される() {
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

```suggestion
    func test_天気予報がrainyだったときに画面に雨画像が表示される() {
```

2021-06-18 15:31 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    }
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

今回関係のないテストコードは削除しておいてもらえると嬉しいです。

```suggestion
```

2021-06-18 15:31 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +        struct MaxTemperature: Testable {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

Stub 実装が冗長なので、ここでは個別に最高気温が受け取れるようにしているので、天気についても同様に受け取れるようにし、それらを統合し、任意の Stub を生成できるヘルパとしてテスト用に用意すると良いと思いました。

2021-06-18 15:31 UTC, ykws commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +    var weatherModel: Testable
別コメントの通り、実装は問題ないけど命名がテストに依存しているように見えるのが引っかかりました。

2021-06-20 23:26 UTC, rizumita requested changes

2021-06-20 23:26 UTC, rizumita commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +    func changeDisplay(_ weatherViewState: WeatherViewState) {
ほとんど意味のないメソッドになってます。
Result<WeatherInformation, WeatherAppError>を引数に取るメソッドにすると良いです。

2021-06-23 04:29 UTC, ykws reviewed
細かい部分ですが、確認お願いします。
レビュー指摘で対応済みのものは resolve できるので、活用すると対応漏れがなくなるかなと思います。

2021-06-23 04:29 UTC, ykws commented on Yumemi-ios-training/Model/Fetchable.swift
> +//  Testable.swift
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

細かいですが、ファイル名 rename すると時はここも
rename のオプションでコメントも含めることができるので活用してもらえればと。

2021-06-23 04:29 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    func test_天気予報がcloudyだったときに画面に晴れ画像が表示される() {
ここ直ってませんでした

2021-06-23 04:29 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    func test_天気予報がrainyだったときに画面に晴れ画像が表示される() {
ここも直ってませんでした

2021-06-23 07:01 UTC, ykws reviewed
1つ追加で気になってしまったので質問です！

2021-06-23 07:01 UTC, ykws commented on Yumemi-ios-training/Controller/WeatherViewState.swift
> +struct WeatherViewState: Equatable {
![ask-badge](https://img.shields.io/badge/review-ask-blue.svg)

これ Equatable にしたのはなぜでしたか？

2021-06-23 07:12 UTC, ykws approved these changes
![LGTM](https://image.lgtmoon.dev/23565)

2021-06-23 07:14 UTC, merged