Session9
Hyperbolic4183/YumemiWeather pull request #15
Opened 2021-06-25 02:01 UTC by Hyperbolic4183

## 行ったこと
- 呼び出しAPIをSync verに変更した
- APIの処理が戻るまでUIActivityIndicatorを表示するようにした

## 工夫したところ
- 時間のかかる処理とその間インジケータを表示させる処理を切り分けた。(showIndicator)

## 懸念点
- 切り分けた関数が読みにくいのではないか
- @escaping, @autoclosure を多く使っており、他に良いやり方があるのではないか
- 可読性を上げるために切り分けたが、返って読みにくくなってしまったのではないか

2021-06-30 06:35 UTC, novr commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +    func showIndicator(result:@escaping @autoclosure () -> Result<WeatherInformation, WeatherAppError>, while processing: @escaping (_ result: Result<WeatherInformation, WeatherAppError>) -> Void) {
変数名に違和感
processingとcompletionでは？

processing中にshowIndicatorし、完了後にcompletionを実行するメソッドなので

2021-06-30 06:35 UTC, novr commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +    func showIndicator(result:@escaping @autoclosure () -> Result<WeatherInformation, WeatherAppError>, while processing: @escaping (_ result: Result<WeatherInformation, WeatherAppError>) -> Void) {
呼び出し側でweatherModel.fetchYumemiWeatherを渡せば@autoclosureは不要です

2021-06-30 06:35 UTC, novr commented on Yumemi-ios-training/View/WeatherView.swift
> +    let indicator = UIActivityIndicatorView()
[IMO]
WeatherViewのプロパティが公開されているので、WeatherViewControllerが内部実装に依存してしまっています
privateして、公開メソッド経由の操作にすると疎結合にすることができます

2021-06-30 06:54 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +    func showIndicator(result:@escaping @autoclosure () -> Result<WeatherInformation, WeatherAppError>, while processing: @escaping (_ result: Result<WeatherInformation, WeatherAppError>) -> Void) {
レビューありがとうございます！

2021-07-02 07:42 UTC, novr requested changes

2021-07-02 07:42 UTC, novr commented on Yumemi-ios-training/View/WeatherView.swift
> +    func operateIndicator() {
[IMO] どんな操作か不明なメソッド名です

2021-07-02 07:42 UTC, novr commented on Yumemi-ios-training/View/WeatherView.swift
> +        reloadButton.addTarget(self, action: action, for: .touchUpInside)
[IMO] delegateパターンを使ってみましょう
```
protocol WeatherViewDelegate: AnyObject {
  func didTapReloadButton(_ view: WeatherView)
  func didTapCloseButton(_ view: WeatherView)
}
```

2021-07-02 07:42 UTC, novr commented on Yumemi-ios-training/View/WeatherView.swift
> +        reloadButton.addTarget(self, action: action, for: .touchUpInside)
対象が違います

2021-07-07 01:30 UTC, novr requested changes

2021-07-07 01:30 UTC, novr commented on Yumemi-ios-training/View/WeatherView.swift
> +    var delegate: WeatherViewDelegate?
delegateはweakで宣言しましょう
https://qiita.com/eKushida/items/d526b0c6d0e3221e77e0

WeatherViewControllerがcloseされても解放されません

WeatherViewControllerにdeintを書いてweakの有無でどうかわるか確認してみましょう
```
deinit {
	print("WeatherViewController　released")
}
```

2021-07-07 01:30 UTC, novr commented on Yumemi-ios-training/View/WeatherViewDelegate.swift
> +protocol WeatherViewDelegate: AnyObject {
WeatherView用のDelegateなので、WeatherView.swiftファイルに書くのが一般的です

```
protocol WeatherViewDelegate: AnyObject {
	...
}

final class WeatherView: UIView {
	...
}
```

2021-07-07 02:07 UTC, novr approved these changes
![LGTM](https://image.lgtmoon.dev/37020)

2021-07-07 02:07 UTC, novr commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +    }
[IMO] delegateの対応部分をextensionで書くこともできます

```swift
final class WeatherViewController: UIViewController {
	...
}

// MARK:- WeatherViewDelegate

extension WeatherViewController: WeatherViewDelegate {

	func didTapReloadButton(_ view: WeatherView) {
		...
	}

	func didTapCloseButton(_ view: WeatherView) {
		...
	}
}
```

2021-07-07 02:07 UTC, novr commented on Yumemi-ios-training/View/WeatherView.swift
> +        indicator.translatesAutoresizingMaskIntoConstraints = false
[NITS] 重複

2021-07-07 02:28 UTC, merged

2021-07-07 02:28 UTC, daichikuwa0618 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +                self.weatherView.switchIndicatorAnimation()
[IMO]
`showIndicator` というメソッド名であるのに「インジケータの表示」以外の責務を負っています。

- インジケータを表示するメソッド (仮名: `showIndicator`)
- `fetchYumemiWeather` を呼び出して `completion` を受け取り処理するメソッド (仮名 `fetch`)
- インジケータを非表示にするメソッド (仮名: `hideIndicator`)

を用意して、以下のように呼び出すと、各関数の凝集度が上がると思います。
(最近コードを追えてないので、処理の内容とか微妙に違ったらすみません。)

```swift
private func reload() {
    
    showIndicator()

    fetch() { [weak self] result in
        self?.updateView(result)
        self?.hideIndicator()
    }
}
```

ここで、凝集度に触れておくと、まず各関数は「機能的強度」と言っていいでしょう。
さらに、 `reload` については「時間的強度」となって変わってないですが、一つ一つの処理が機能的強度の関数でまとめられているので、見通しも良くなるきがします。

ここは好みかもしれないですが、 `switchIndicatorAnimation` を直接呼ぶと状態管理をする必要が出てきてしまうので、わざわざ対称性を持つ 2 つのメソッドに分けてみました。

2021-07-07 08:19 UTC, rizumita commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +                self.weatherView.switchIndicatorAnimation()
[IMO]
showIndicator()とhideIndicator()を対にして利用する必要があるのでreloadという文脈で管理するのはhideの呼び忘れが発生する可能性があります。ですのでshow/hideを行っている元のメソッドの方が安定していると考えます。引数ラベルをshowIndicator(while:completion:)のように変更するとwhile中にのみIndicatorを表示するという意味になって責務が限定されているのが分かると思います。

それからshowIndicatorのResult<WeatherInformation, WeatherAppError>はジェネリクスで抽象化するとprocessingとcompletionの結びつきが強く表現できます。