Session10
Hyperbolic4183/YumemiWeather pull request #18
Opened 2021-07-07 12:29 UTC by Hyperbolic4183

## 行ったこと
- モデルクラスFetcherのYumemiWeatherパッケージに依存していた部分をデリゲートパターンを使って別のクラスに委譲させ得るようにした。

## 懸念点
- モデルクラスFetcherの命名: Fetcherからfetch機能を委譲させたから変えた方がよかったか？
- Fetcher.swiftのファイルの内容は二つに分けた方がいいか。;YumemiWeatherに依存しているのはプロトコルだけなので
- デリゲートメソッド名に違和感はないか

2021-07-07 12:38 UTC, rizumita requested changes

2021-07-07 12:38 UTC, rizumita commented on Yumemi-ios-training/Model/Fetcher.swift
> +protocol FetcherDelegate: AnyObject {
Delegationは複数の処理の差し替えを実現するデザインパターンですが、差し替えが必要でしょうか？

2021-07-07 12:38 UTC, rizumita commented on Yumemi-ios-training/Model/FetchYumemiWeather.swift
> +    func didFetchSyncFetchWeather(_ jsonString: String) throws -> String {
didFetchはFetchの完了を表しますが、おそらくこのメソッドはFetchをこれから行うという事だと思いますので、命名が不適切だと考えられます。
またStringを返すようなメソッド名になっていません。Fetch処理を委譲されるという事でしたらfetch…でよいと考えられます。

2021-07-07 12:38 UTC, rizumita commented on Yumemi-ios-training/Model/FetchYumemiWeather.swift
> +    func didOccurError(from error: Error) -> YumemiWeatherError? {
こちらの命名もdidFetchSyncFetcherWeatherと同様に問題があります。

2021-07-07 16:00 UTC, ykws requested changes
Delegate の理解としてこちらも参考になるかもです。イラストなのでイメージしやすいはず。

[【swift】イラストで分かる！具体的なDelegateの使い方。](https://qiita.com/chanNaru/items/326bd50a78cf34371169)

身近なところだと iOS App の雛形として生成される部分も Delegate パターンになっています。

- [AppDelegate](https://github.com/Hyperbolic4183/YumemiWeather/blob/main/Yumemi-ios-training/AppDelegate.swift) - [UIApplicationDelegate](https://developer.apple.com/documentation/uikit/uiapplicationdelegate)
- [SceneDelegate](https://github.com/Hyperbolic4183/YumemiWeather/blob/main/Yumemi-ios-training/SceneDelegate.swift) - [UISceneDelegate](https://developer.apple.com/documentation/uikit/uiscenedelegate)

2021-07-07 16:00 UTC, ykws commented on Yumemi-ios-training/Model/Fetcher.swift
> +    func didOccurError(from error: Error) -> YumemiWeatherError?
![must-badge](https://img.shields.io/badge/review-must-red.svg)

位置情報をリクエストして結果を受け取る [CLLocationManagerDelegate](https://developer.apple.com/documentation/corelocation/cllocationmanagerdelegate) が今回のやりたいことのイメージに近いと思います。

位置情報の更新が発生した。
`func locationManager(CLLocationManager, didUpdateLocations: [CLLocation])`

エラーが発生した
`func locationManager(CLLocationManager, didFailWithError: Error)`

これに習って以下を定義するにはどうするのが良いか考えてみてください。

- 天気予報の更新が発生した
- エラーが発生した

2021-07-07 16:00 UTC, ykws commented on Yumemi-ios-training/Model/Fetcher.swift
>      func fetchYumemiWeather() -> Result<WeatherInformation, WeatherAppError> {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

Delegate パターンを利用することで、リクエストは投げっ放しになり、 Delegate で状態の変化を受け取ることになるので、 fetchYumemiWeather としては `return` は不要にできます。共存させても NG ではないですが、

こちらも位置情報の例ですが、 [requestLocation()](https://developer.apple.com/documentation/corelocation/cllocationmanager/1620548-requestlocation) のようなイメージになります。

2021-07-07 16:00 UTC, ykws commented on Yumemi-ios-training/Model/FetchYumemiWeather.swift
> +class FetchYumemiWeather: FetcherDelegate {
![ask-badge](https://img.shields.io/badge/review-ask-blue.svg)

同期APIから天気予報を受け取りたいのは FetchYumemiWeather でしょうか？

2021-07-09 01:24 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Model/FetchYumemiWeather.swift
> +class FetchYumemiWeather: FetcherDelegate {
@ykws 
そうですね。同期APIとのつながりは全てここに任せるつもりです。

2021-07-16 08:45 UTC, daichikuwa0618 reviewed
至るところに試行錯誤の跡が見られて、とても考えられていると思います！
(自分がやってたときの数倍考えれてる気がする、、、)

もうエラーハンドリングとか Optional Binding はバッチリだと思いました！！

少しだけ命名とかで気になった箇所があったのでコメントしています。

2021-07-16 08:45 UTC, daichikuwa0618 commented on Yumemi-ios-training/Controller/InitialViewController.swift
> +    //let fetchYumemiWeather = FetchYumemiWeather.shared
これ要らなさそうです。

2021-07-16 08:45 UTC, daichikuwa0618 commented on Yumemi-ios-training/Model/Fetcher.swift
> +//  WeatherAppManager.swift
ここ Fetcher のままでいいような

2021-07-16 08:45 UTC, daichikuwa0618 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +        result = .failure(error)
折角 Delegate で成功/失敗が分かれているので、 result っていうプロパティに格納しなくても、

- 成功したときに `information` から View を更新する関数
- 失敗したときに `error` からハンドリングする関数

を VC に作ってそれぞれで処理させると処理が分かれて良さそうだと思ったのですが、どうでしょうか。

2021-07-16 08:45 UTC, daichikuwa0618 commented on Yumemi-ios-training/Model/Fetcher.swift
> +    func fetchManager(_ manager: Fetcher, didFailWithError error: WeatherAppError)
```suggestion
protocol FetcherDelegate: AnyObject {
    func fetcher(_ fetcher: Fetcher, didReload information: WeatherInformation)
    func fetcher(_ fetcher: Fetcher, didFailWithError error: WeatherAppError)
```

ですかね？

2021-07-16 16:03 UTC, ykws requested changes
Delegate の部分は良いと思いました！
ViewController が Fetchable の実装に依存するようになってしまったので、インターフェースに依存するようにしてみてください。

2021-07-16 16:03 UTC, ykws commented on Yumemi-ios-training/Controller/InitialViewController.swift
> +        let weatherViewController = WeatherViewController(model: fetcher)
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

fetcher を別で使うわけではないようなので、変更前の状態でも良さそうですね

2021-07-16 16:03 UTC, ykws commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +    func fetcher(_ manager: Fetcher, didReload information: WeatherInformation) {
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

ここも fetcher に直すなら統一したい
```suggestion
    func fetcher(_ fetcher: Fetcher, didReload information: WeatherInformation) {
```

2021-07-16 16:03 UTC, ykws commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +    func fetcher(_ manager: Fetcher, didFailWithError error: WeatherAppError) {
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

ここも fetcher に直すなら統一したい

```suggestion
    func fetcher(_ fetcher: Fetcher, didFailWithError error: WeatherAppError) {
```

2021-07-16 16:03 UTC, ykws commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +            guard let _result = result else {
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

`_` 付けなくても大丈夫ですよ

```suggestion
            guard let result = result else {
```

2021-07-16 16:03 UTC, ykws commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +    init(model: Fetcher) {
![must-badge](https://img.shields.io/badge/review-must-red.svg)

Fetcher は Fetchable の実装なので、 Fetchable = protocol のまま受け取れる方がインターフェースに依存しているのでいるのでより良いです。

2021-07-16 16:47 UTC, novr commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +    var result: Result<WeatherInformation, WeatherAppError>?
[IMO] 外部から参照する必要のないプロパティはなるべくprivateに

2021-07-16 16:47 UTC, novr commented on Yumemi-ios-training/Model/Fetcher.swift
> +    func fetcher(_ fetcher: Fetcher, didReload information: WeatherInformation)
[IMO] didReloadはView側の動作です、FetcherとしてはdidFetchでは？

2021-07-16 16:47 UTC, novr commented on Yumemi-ios-training/Model/Fetcher.swift
> +                return
[NITS] didFailWithErrorに通知はしない？

2021-07-16 16:47 UTC, novr commented on Yumemi-ios-training/Model/Fetcher.swift
> +                return
[NITS] didFailWithErrorに通知はしない？

2021-07-16 16:47 UTC, novr commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +            processing()
[NEXT] 処理が非同期だった場合どうなるでしょうか？
https://github.com/yumemi-inc/ios-training/blob/main/Documentation/YumemiWeather.md#async-ver

2021-07-21 07:55 UTC, daichikuwa0618 reviewed
外部引数名の命名は意外と奥深いと思うので、考えてみてくださいー

2021-07-21 07:55 UTC, daichikuwa0618 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +        updateView(success: information)
[IMO]
外部引数名で成功・失敗分けるのいいですね！！

ただ、これだと「成功を渡す」感じがしちゃうので `updateView(onSuccess: information)` みたいな命名はいかがでしょうか？

2021-07-21 07:55 UTC, daichikuwa0618 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +        updateView(failure: error)
こっちも `updateView(onFailure: error)` のほうがわかりやすそうです。

2021-07-21 07:55 UTC, daichikuwa0618 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +    func updateView(success information: WeatherInformation) {
`private` にできますね。

2021-07-21 07:55 UTC, daichikuwa0618 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +    func updateView(failure error: WeatherAppError) {
こっちも `private` にできますね。

2021-07-21 16:26 UTC, novr commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +        }
[ASK] 何目的のキュー切り替えでしょうか？

2021-07-21 16:26 UTC, novr commented on Yumemi-ios-training/Controller/WeatherViewController.swift
>          globalQueue.async {
[ASK] globalQueueでの実行処理がありませんが必要ですか？

2021-07-21 16:26 UTC, novr commented on Yumemi-ios-training/Controller/WeatherViewController.swift
>      func didTapReloadButton(_ view: WeatherView) {
[IMO] @objc func reload(_ sender: UIButton)と同じイベント処理ならば、共通化してもよいかと

2021-07-21 16:26 UTC, novr commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +            mainQueue.async { [self] in
[ASK] キャプチャリストの意味は理解していますでしょうか？
この場合、selfを強参照します

2021-07-28 00:50 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +            mainQueue.async { [self] in
していないです。


ここで弱参照ではなく強参照してしまうことのデメリットについて考えてみたのですが、合っているでしょうか？
- mainQueue.async {} 内の関数の実行中は`WeatherViewController`の解放が行われない可能性がある

2021-07-28 01:34 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +        }
前まで使っていた`showIndicator()`をそのまま使っていました。

今は必要のないキュー切り替えです。

2021-07-28 01:36 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
>          globalQueue.async {
これも上と同様に必要ないです。

2021-07-28 01:42 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
>      func didTapReloadButton(_ view: WeatherView) {
同じイベントを別の関数で分けていて、さらにそこに時間のかかる処理も含まれているので書きにくくて読みにくいんですよね。
共通化します。

2021-07-30 09:08 UTC, daichikuwa0618 reviewed
`reload` を連打すると連続で fetch されます。
ローディング中は操作をさせないようにするのが一般かと思います。

操作をさせないためには

- View 全体を囲う `isUserInteractionEnabled = false` の View を重ねる
  - `ActivityIndicator` を上に乗っけて `LoadingView` みたいなのを作ってもいいと思います
- `DispatchSemaphore` を使ってメインスレッドをブロックする
  - ちょっと大変かもですが、こんなやりかたもあります。

https://user-images.githubusercontent.com/31601805/127629828-86f01f7f-46c9-4152-aba1-6b5114608146.mov

2021-07-30 09:08 UTC, daichikuwa0618 commented on Yumemi-ios-training/Model/Fetcher.swift
> +    let globalQueue = DispatchQueue.global(qos: .userInitiated)
`private` でよさそうです。

2021-07-30 12:37 UTC, ykws reviewed
コメントしましたので、 protocol として定義した Delegate が何に依存していて、何に依存していないか、見直しをお願いします。

2021-07-30 12:37 UTC, ykws commented on Yumemi-ios-training/Model/Fetcher.swift
> +}
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

Fetchable の Delegate なので FetchableDelegate が適切で、 protocol の定義は Fetchable と同じ箇所にあるのが望ましいです。

合わせて Fetchable の Delegate なので protocol の定義は Fetchable  に統一して、 Fetcher には依存していないのが明確になっていると良いです。（メソッド名は動詞が良いので fetch）

```suggestion
protocol FetcherDelegate: AnyObject {
    func fetch(_ fetchable: Fetchable?, didFetch information: WeatherInformation)
    func fetch(_ fetchable: Fetchable?, didFailWithError error: WeatherAppError)
}
```

まとめると、 Fetchable は protocol なので、 Fetcher に依存しないようにします。
具体的には Fetcher を Fetchable を実装した別の何かと入れ替えても大丈夫なようになっていれば依存していないと言えます。
現状は、例えば、 Fetcher を入れ替えて削除するとなったら、 FetcherDelegate も削除されてしまうので良くないです。

2021-07-30 12:37 UTC, ykws commented on Yumemi-ios-training/Model/Fetcher.swift
> +class Fetcher: Fetchable {
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

継承させないなら `final` をつけましょう。

```suggestion
final class Fetcher: Fetchable {
```

2021-07-30 12:37 UTC, ykws commented on Yumemi-ios-training/Model/Fetcher.swift
> +        globalQueue.async { [weak self] in
![ask-badge](https://img.shields.io/badge/review-ask-blue.svg)

⬇️  これだと問題ありましたか？

```suggestion
        DispatchQueue.global().async { [weak self] in
```

2021-07-30 12:37 UTC, ykws commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +        var message = ""
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

必ず初期化されるので、こうした方が意図を明確にできます。

```suggestion
        let message: String
```

2021-07-30 13:34 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Model/Fetcher.swift
> +        globalQueue.async { [weak self] in
問題ありません。なんとなく変数にした方がいいかなと思って一旦変数にしました。

2021-07-30 13:40 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +        var message = ""
これコンパイル通るんですね。

2021-08-02 08:02 UTC, novr commented on Yumemi-ios-training/Model/Fetcher.swift
> +    let globalQueue = DispatchQueue.global(qos: .userInitiated)
使われてないです

2021-08-10 22:52 UTC, ykws approved these changes
1点コメントしましたが、全体としては良さそうです！

![LGTM](https://image.lgtmoon.dev/77676)

2021-08-10 22:52 UTC, ykws commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +        weatherView.switchIndicatorAnimation()
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

switchLoadingView と switchIndicatorAnimation は毎回セットで呼んでいるようなので外部から見た WeatherView の振る舞いとしてはまとめてしまって良さそうです。呼び漏れがあっても困ると思うので、そういったミスも防げるようになります。

2021-08-11 01:25 UTC, merged