asyncFetchWeatherに対応させた。
Hyperbolic4183/YumemiWeather pull request #19
Opened 2021-08-11 01:53 UTC by Hyperbolic4183

## 行ったこと
YumemiWeather.asncFetchWeather()に変更した。

## 懸念点
特になし

2021-08-11 15:34 UTC, ykws requested changes
すみません、前回の Session マージの段階でテストが壊れていたので改善をお願いします。
PR チェック用のテストがパスすることを確認する GitHub Actions を走らせても良さそう

この PR は Session11 で良かったでしょうか？（タイトルが Session10 になっていたので）

2021-08-18 09:34 UTC, Hyperbolic4183 commented
@ykws 
mainブランチにGitHub actions走らせてみました。
sesseion11 はコールバックによる実装なので、別ですね。asncを使ったsessionは現在ないようです。

2021-08-18 10:12 UTC, daichikuwa0618 requested changes
`Pods/` を無視してもらえますでしょうか。

2021-08-18 11:14 UTC, novr requested changes
PRとしての内容がぶれてきています
一度、問題を分割して対応した方がよさそうです

2021-08-18 11:14 UTC, novr commented on Yumemi-ios-training/Model/Fetchable.swift
> +    func fetch(completion: (()->Void)?)
このcompletionは何でしょうか？

2021-08-18 11:14 UTC, novr commented on Yumemi-ios-training/Model/Fetcher.swift
> +    func fetch(completion: (() -> Void)?) {
completionは呼ばれないが何のために？

2021-08-18 11:14 UTC, novr commented on Yumemi-ios-training/Model/Fetcher.swift
> -                    self?.delegate?.fetch(self, didFailWithError: .unknownError)
assertionFailureだと、Releaseの時にエラーが通知されません

2021-08-18 11:14 UTC, novr commented on Yumemi-ios-training/Model/Fetcher.swift
> +        YumemiWeather.asyncFetchWeather("{\"area\": \"tokyo\", \"date\": \"2020-04-01T12:00:00+09:00\" }") { result in
selfはキャプチャ不要でしょうか？

2021-08-18 11:14 UTC, novr commented on Yumemi-ios-training/View/WeatherView.swift
> +final class TestWeatherView: WeatherView {
Testのためのクラスでしょうか？
一般的にTestのためのクラスはTestターゲットにおきます

2021-08-18 23:26 UTC, ykws commented
> sesseion11 はコールバックによる実装なので、別ですね。asncを使ったsessionは現在ないようです。

@Hyperbolic4183 Session10 は #18 で済んでいる認識なのですが、どの課題をやられていますか？

2021-08-19 09:28 UTC, daichikuwa0618 reviewed
もしかして今取り組まれてるのって
https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Closure.md

> ぜひ関数型引数はOptional型、非Optional型の両方を実装し

でしょうか？

2021-08-19 09:28 UTC, daichikuwa0618 commented on Yumemi-ios-training/View/WeatherView.swift
> +    private(set) var weatherImageView = UIImageView()
テストのために露出してる感じですか？

テストのためだけだったら、あまり実装を変えたくないので、以下のようにして View の構造ありきで取得するのもありかとおもいます。

https://github.com/daichikuwa0618/YumemiTraining/blob/1901047a3dff3ec7cefec9c6c82d30306b478016/YumemiTraining/YumemiTrainingTests/WeatherViewControllerTests.swift#L78-L84

```swift
    private func getImageView(from vc: WeatherViewController) -> UIImageView {
        let weatherView: WeatherView = vc.view.subviews.first! as! WeatherView
        weatherView.layoutIfNeeded()
        let stackView: UIStackView = weatherView.subviews.first(where: { $0 is UIStackView })! as! UIStackView
        let imageView: UIImageView = stackView.subviews.first(where: { $0 is UIImageView })! as! UIImageView

        return imageView
    }
```

2021-08-19 09:28 UTC, daichikuwa0618 commented on Podfile
> +  pod 'Runtime'
このライブラリ使われてない気がします。

2021-08-21 03:04 UTC, ykws commented
@Hyperbolic4183 
Session として用意されている課題とは別に [asyncFetchWeather](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/YumemiWeather.md#async-ver) を試している PR と理解しました。
（そういえば、この Session が不足しているというコメントがありましたね。別途本家に Session 追加の PR を作成してみます）

現状はこの PR に二つの課題が混ざってしまっているので、分けてみましょう。

1. まず、テストが壊れている Issue を作成する
2. テストを修正する PR を別に作成する
3. テスト修正の 2 の PR ベースにこの PR を対応する

これにより、テスタブルな構造の変更と非同期のテストの問題を分けることができます。

2021-08-23 07:06 UTC, merged