壊れたテストの修正
Hyperbolic4183/YumemiWeather pull request #31
Opened 2021-08-25 00:40 UTC by Hyperbolic4183

## 目的
ユニットテストによって安全性を保障すること
## 実装の概要
1 `WeatherView`の`changeDisplay()`が正常に動くことを`XCTAssertEqual()`によって確かめる。
2 `WeatherView`のプロパティであるUI部品を`subViews`などによって取り出す。
## レビューして欲しいところ
1における書き方、テストとして十分か
2のようなUI部品を取り出す方法について、他に方法などがあれば教えて欲しい。

2021-08-25 01:21 UTC, daichikuwa0618 approved these changes
自分の手元でもテスト通りました！！ 💯 

`hotfix` っていうのはリリースしてからバグが見つかってすぐに修正したいってときに使うブランチ名なので、ここは普通に `fix/XCTest` で良いかもと思いました。

今 Git-flow 使われてるわけではないので、特に気にしなくて OK ですが、一応ブランチ名はそんな感じ使い分けしますってことだけお伝えしました。

2021-08-25 01:21 UTC, daichikuwa0618 commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
>      func test_天気予報がcloudyだったときに画面に曇り画像が表示される() {
[NITS]
`func` 同士で空行があったりなかったりするので、全部空行入れたほうがみやすいかもです

2021-08-25 01:21 UTC, daichikuwa0618 commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +        view.subviews.first(where: { $0 is UIStackView})! as! UIStackView
テストのときは積極的に force unwrapping や force cast 使えばいいと思うので、いい感じです 👍

2021-08-31 01:17 UTC, ykws requested changes
テストパスすることは確認できましたが、
テストしたい観点がズレてしまっているので見直しをお願いします。

2021-08-31 01:17 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> -    func fetchYumemiWeather() -> Result<WeatherInformation, WeatherAppError> {
変更前の状態は Model の IF を含めた**天気予報を取得し、結果を表示するというシナリオ**もテストできていたので、元の状態でテストできるように見直しをお願いします。

2021-08-31 01:27 UTC, ykws approved these changes
#32 もこの PR に依存しているようなので、一旦テスト修復できた状態をマージして Model のテストは別対応にしても良いと思いました。

2021-08-31 05:44 UTC, daichikuwa0618 approved these changes

2021-08-31 06:04 UTC, merged