XCTestのテスト対象を変更した
Hyperbolic4183/YumemiWeather pull request #33
Opened 2021-09-01 09:12 UTC by Hyperbolic4183

## 目的
XCTestの対象をViewからModel、Viewを含めたViewControllerに変更すること
## 実装の概要
- `Fetchable`プロトコルに準拠した`FetcherMock`を作成し、'WeatherViewController'に注入している。
- 'WeatherViewController'はViewの更新に非同期処理を含んでいるので、'XCTestExpectation'を使った。
- `addProcessing(target: Void,completion: @escaping () -> Void)`を定義し、ボタンを押した後に、テスト項目の処理を加えられるようにした。
## レビューして欲しいところ
- `addProcessing(target: Void,completion: @escaping () -> Void)`を定義する以外に非同期処理をテストするための実装が思い浮かばなかった。ボタンを押した後に非同期処理が入る場合、どのようにテストをするのが良いか教えて欲しい。

2021-09-02 04:24 UTC, ykws reviewed
まず Button タップを実装し直すのは、非同期処理が冗長なため、しなくて良いと思いました。
現状規定してもらっている protocol ベースでテストしたいシナリオを以下に整理してみます。

### テストしたいシナリオ
- Fetchable の fetch を通して天気予報の取得を要求する
- FetchableDelegate の fetch を経由して天気予報の結果を取得する
- WeatherView に天気予報の結果が表示される

`WeatherViewController` に対してのアクセスを制限しているのと、
`FetchableDelegate` で ViewController を Mock できるのでテストしたいシナリオを以下のように確認できると良さそうです。

- FetchableDelegate を実装して ViewController を Mock する
  - ViewController Mock に検証用の WeatherView を持たせる
  - FetchableDelegate の fetch を実装して WeatherView を更新する
  - ViewController Mock の WeatherView を検証する

ViewController を Mock するので非同期のことは意識しないで済むようになります。

2021-09-02 08:14 UTC, ykws approved these changes
いくつかコメントはしましたが、 protocol ベースでテストできているので良いと思いました！

![LGTM](https://image.lgtmoon.dev/90452)

2021-09-02 08:14 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +
![memo-badge](https://img.shields.io/badge/review-next-blueviolet)

エラーパターンもテストできると良いです

2021-09-02 08:14 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    let maxTemperature: String
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

`weatherInformation` 以外は参照しないので `init` で直接 `WeatherInformation` に渡してしまえば定義しなくても良いです

2021-09-02 08:14 UTC, ykws commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +    private(set) var weatherModel: Fetchable
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

ViewController Mock しているので変更不要になってますか？

2021-09-02 08:14 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +        weatherViewControllerMock.model.fetch()
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

Model と ViewController は依存していないので、無理に持たせなくても良いです
一例として、

```suggestion
        weatherViewControllerMock = WeatherViewControllerMock()
        fetcherMock.delegate = weatherViewControllerMock
        fetcherMock.fetch()
```

2021-09-02 20:59 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +
## エラーのシナリオ
- Fetchable の fetch を通して天気予報の取得を要求する
- FetchableDelegate の fetch を経由して天気予報のエラーを取得する

WeatherView に対する更新は特にないため、
エラーを返す Fetchable の Mock を用意して、 FetchableDelegate でエラーの処理が呼ばれることを確認できれば良いと思います。呼ばれるかどうかは XCTestExpectation が使えます。

現状はエラーの表示が ViewController に依存しているので、
今の時点はこれくらいで良いと思いますが、
この部分も Controller から分離して View のテストができるようにすると良いです。

2021-09-03 00:47 UTC, novr commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +        weatherViewControllerMock = WeatherViewControllerMock(model: fetcherMock)
[ASK] テスト対象は何でしょうか？
FetcherMockの結果を使ってWeatherViewControllerMockをテストしています

2021-09-05 21:43 UTC, ykws commented on Yumemi-ios-trainingTests/WeatherViewControllerMock.swift
> +    var model: Fetchable?
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

使ってないです

2021-09-05 22:12 UTC, ykws commented on Yumemi-ios-trainingTests/FailedFetcherMock.swift
> +import Foundation
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

import しなくて大丈夫です

2021-09-05 22:12 UTC, ykws commented on Yumemi-ios-trainingTests/SuccessFetcherMock.swift
> +import Foundation
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

import しなくて大丈夫です

2021-09-05 22:12 UTC, ykws commented on Yumemi-ios-trainingTests/WeatherViewControllerMock.swift
> +import Foundation
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

import しなくて大丈夫です

2021-09-05 22:12 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    private func getReloadButton(from view: UIView) -> UIButton {
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

使わなくなってますかね？

2021-09-05 22:12 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +extension XCTestExpectation {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

なんだろうと思ってしまったので、
単に Delegate に対して expectation を渡して、 `fulfill()` すれば良いと思いました。

2021-09-05 22:12 UTC, ykws commented on Yumemi-ios-trainingTests/SuccessFetcherMock.swift
> +    func fetch() {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

成功と失敗の Mock を分けずに、 error のプロパティを持たせて、
エラーを注入できるようにし、エラーの場合に `didFailWithError` を呼んで良いと思います。

2021-09-05 22:12 UTC, ykws commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    func test_Fetcherでエラーが起きた時にWeatherViewControllerのdelegateが動く() {
![suggestion-badge](https://img.shields.io/badge/review-suggestion-blue.svg)

この形式に合わせて表現を見直してみてください

`天気予報がsunnyだったときに画面に晴れ画像が表示される`

`天気予報が〇〇だったときに〇〇される`

2021-09-13 04:28 UTC, novr requested changes

2021-09-13 04:28 UTC, novr commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(reload), name: UIApplication.didBecomeActiveNotification, object: nil)
[NITS] 今回の内容と別ですが
reloadメソッド内でViewへアクセスしているのでviewDidLoad以後に登録のがよいかと思います

2021-09-13 04:28 UTC, novr commented on Yumemi-ios-trainingTests/FetcherMock.swift
> +    let isFetchSucceed: Bool
[IMO] `Result<WeatherInformation, WeatherAppError>`型で表現できる

2021-09-13 04:28 UTC, novr commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +    init(model: Fetchable, queueScheduler: MainQueueScheduler, errorHandler: ErrorHandler) {
[IMO] default引数とすると1つに集約できそうです
```suggestion
    init(model: Fetchable, queueScheduler: MainQueueScheduler = .live, errorHandler: ErrorHandler = .presentAlertViewController) {
```

2021-09-13 04:28 UTC, novr commented on Yumemi-ios-training/Controller/ErrorHandler.swift
> +    switch error as! WeatherAppError {
[MUST] WeatherAppErrorに強制キャストしている
WeatherAppError型に限定するか、unknownErrorにフォールバックすべき

2021-09-13 04:28 UTC, novr commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +    var weatherModel: Fetchable
[IMO] Testで`weatherViewController.weatherModel.fetch()`するために公開範囲を変えるよりは
Testでは`fetcherMock.fetch()`を呼び出していいかと
`test_最低気温がUILabelに反映される()`ではfetcherMock.fetch()で対応している

2021-09-13 04:28 UTC, novr commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    private func getImage(from view: UIView) -> UIImage {
[MUST] XCTAssertEqualはnilとも比較してくれるので戻り値はUIImage?として、!しない

2021-09-13 04:28 UTC, novr commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
>          //WeatherView含まれる2つのUIStackViewのうち、2番目に追加したstackViewForLabelsを取得
[NITS] UI構造に依存してしまうのでaccessibilityIdentifierなど活用してもよいかと

2021-09-13 04:28 UTC, novr commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +    var fetcherMock: FetcherMock!
[IMO] test間を超えてアクセスしたりsetup等でインスタンス化するわけではないので、メソッド内変数でよさそうです

2021-09-14 08:57 UTC, novr requested changes

2021-09-14 08:57 UTC, novr commented on Yumemi-ios-trainingTests/Yumemi_ios_trainingTests.swift
> +            .filter{$0.accessibilityIdentifier == AccessibilityIdentifier.stackViewForImageViewAndLabels}
[MUST] [【TIPS】今すぐ `.filter{...}.first` をやめましょう](https://qiita.com/lovee/items/eb6ce12408d85a1bb23a)

2021-09-14 09:39 UTC, novr approved these changes
![LGTM](https://image.lgtmoon.dev/135789)

2021-09-16 06:06 UTC, merged