Session2
Hyperbolic4183/YumemiWeather pull request #4
Opened 2021-05-12 03:19 UTC by Hyperbolic4183

## 行ったこと
reloadボタンが押された時に、fetchWeather()で返された値によって画像を変更されるようにした。

## 工夫したところ
- ビジネスロジックだけを取り出し、ビューを描画するファイルと切り分けた。

レビューよろしくお願いします！

2021-05-12 09:44 UTC, daichikuwa0618 requested changes
いくつか diff をみて気になったことをレビューしました。

2021-05-12 09:44 UTC, daichikuwa0618 commented on Yumemi-ios-training/Assets.xcassets/sunny.imageset/Contents.json
> +      "filename" : "sunny.png",
[課題](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/API.md) を見ると、 pdf の画像が指定されていそうです。

ラスター画像とベクター画像ではちょっと扱いが違うので、できれば指定通り PDF で実装していただいていいですか？

2021-05-12 09:44 UTC, daichikuwa0618 commented on Yumemi-ios-training/WeatherDelegate.swift
> +import Foundation
[NITS]

`Foundation` は import 不要そうですね。

2021-05-12 09:44 UTC, daichikuwa0618 commented on Yumemi-ios-training/WeatherModel.swift
> +        print("test")
[NITS]

余計なデバッグ用出力は特に理由がない限り、極力削除して置きたいです。

2021-05-12 09:44 UTC, daichikuwa0618 commented on Yumemi-ios-training/WeatherViewController.swift
> +        weatherModel?.reload(imageView: weatherView.weatherImageView)
[IMO]

`weatherModel` という model 層のオブジェクトが `UIImageView` を操作している作りになっているので、修正が必要かもしれません。

(私なら) `weatherModel` からは天気だけを受け取って、 `WeatherViewController` で表示用のデータ (`UIImage` や `UIColor` を用意し、 `weatherView` に渡して View を更新させるって感じの処理にします。

他の方のアドバイスも聞きながら、考えてみてください。

一つの指標としては、何を import しているかは意識したほうが良いかも知れないです。
`WeatherModel` で `YumemiWeather` (仮想 API) と `UIKit` に依存していますが、これは外部 API と UI 層という離れた層に依存している形になっています。
UI 層オブジェクトであれば UI 関連だけ、 Model (Domain) 層であればロジック関連だけって感じの依存関係で完結するのが理想かと思います。

2021-05-12 09:44 UTC, daichikuwa0618 commented on Yumemi-ios-training/WeatherDelegate.swift
> +protocol WeatherDelegate {
[IMO]
View の Interface を protocol で抽象化しているのはとても良いと思いました！！

せっかく抽象化を理解されているのであれば、 Model も積極的に抽象化する対象です。
理由としては UI よりもテストで出現する頻度が高く、stub/spy に置き換えられる場合が多いためです。

Session8 とかでテストコードは書くことになるので、ここではふーんと流しておいて、そのときに抽象化するでも大丈夫です 👌

2021-05-13 22:52 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Assets.xcassets/sunny.imageset/Contents.json
> +      "filename" : "sunny.png",
@daichikuwa0618
.withRenderingModeで色を変えようとすると白の背景も変わってしまうので背景透過のものに変えてしまったんですよね。PDFのままの実装やってみます！

2021-05-13 22:53 UTC, Hyperbolic4183 commented on Yumemi-ios-training/WeatherDelegate.swift
> +import Foundation
そうですね。消します。

2021-05-13 22:53 UTC, Hyperbolic4183 commented on Yumemi-ios-training/WeatherModel.swift
> +        print("test")
わかりました。

2021-05-13 23:45 UTC, Hyperbolic4183 commented on Yumemi-ios-training/WeatherViewController.swift
> +        weatherModel?.reload(imageView: weatherView.weatherImageView)
切り分けてみました。どうでしょうか？？

2021-05-14 01:05 UTC, daichikuwa0618 reviewed
いくつか気になったのでレビューしました。

2021-05-14 01:05 UTC, daichikuwa0618 commented on Yumemi-ios-training/Assets.xcassets/cloudy.imageset/Contents.json
> +      "scale" : "3x"
[IMO]
pdf はベクター画像なので、特にラスター画像として扱いたい理由がなければそのままベクター画像として扱うのが一般的です。

- `Preserve Vector Data` を ON に
- Scales を `Single Scale` に

することでそのように扱えると思います。
(もし修正するのであれば 3 枚ともお願いします)

参考: https://qiita.com/okamu_/items/085cfc5999db801020ff

<img width="261" alt="スクリーンショット 2021-05-14 9 55 11" src="https://user-images.githubusercontent.com/31601805/118205061-88eb0900-b49a-11eb-9b0f-40a18d1b5e09.png">

2021-05-14 01:05 UTC, daichikuwa0618 commented on Yumemi-ios-training/WeatherDelegate.swift
> +    func reload() -> Dictionary<String, Any>
[IMO]
ここは Dictionary で key が String だと型で縛れないので、表示する用のオブジェクトを作ってその型を返すようにするか、タプルで返すようにすることで型の制約をつけるのが良いと思います。

下記の例では `WeatherViewState` において `weather: String` と `color: UIColor` のプロパティを持っていますが、責務を意識できていれば画像をもたせたりしても良いかも知れないです。

<details><summary><b>型を作る時の例</b></summary><div>

```swift
struct WeatherViewState {
    let weather: String
    let color: UIColor
}

protocol WeatherDelegate {
    func reload() -> WeatherViewState
}
```

</div></details>

<details><summary><b>タプルで返す例</b></summary><div>

```swift
protocol WeatherDelegate {
    func reload() -> (weather: String, color: Color)
}
```

</div></details>

2021-05-14 01:31 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Assets.xcassets/cloudy.imageset/Contents.json
> +      "scale" : "3x"
なるほど、画質の悪い原因はこれだったんですね。

2021-05-14 01:31 UTC, rizumita requested changes

2021-05-14 01:31 UTC, rizumita commented on Yumemi-ios-training/WeatherDelegate.swift
> +protocol WeatherDelegate {
## 命名
WeatherViewのDelegateなのでWeatherView…が良いように思います。データを取得する場合はUIKitでは一般的にDataSourceと命名されています。総合するとWeatherViewDataSourceとなります。

## Delegate内容
Delegateは処理の委譲ですがWeatherViewは「表示を行う」役割なのでreloadは役割として持っていないと考えられます。ですのでDelegateでreloadを委譲するということは無いように思います。

2021-05-14 03:20 UTC, Hyperbolic4183 commented on Yumemi-ios-training/WeatherDelegate.swift
> +protocol WeatherDelegate {
ありがとうございます！

2021-05-14 05:45 UTC, Hyperbolic4183 commented
@rizumita
いただいたレビューを反映させました。確認よろしくお願いします！

2021-05-18 09:07 UTC, ruby109 commented on Yumemi-ios-training/WeatherViewController.swift
> +    var delegate: WeatherViewDataSource?
reloadをViewControllerで行ってたなので、delegateのプロパティーを削除した方が良いと思います。

2021-05-19 00:07 UTC, Hyperbolic4183 commented on Yumemi-ios-training/WeatherViewController.swift
> +    var delegate: WeatherViewDataSource?
コメントありがとうございます。おっしゃる通り不必要なdelegateでした。

2021-05-19 02:01 UTC, rizumita requested changes

2021-05-19 02:01 UTC, rizumita commented on Yumemi-ios-training/SceneDelegate.swift
> +            let weatherViewController = WeatherViewController()
WeatherViewControllerのイニシャライザにweatherModelを渡す形にするとOptionalではなくする事が出来るように思います。

2021-05-19 02:40 UTC, Hyperbolic4183 commented
@Hyperbolic4183 あ

2021-05-19 05:43 UTC, ykws requested changes
ちゃんと View と Model を分ける意図があって良いと思います。
ただ、その責務の分離が明確になっていないように感じました。まだ小さいプログラムなので今の段階ではがんばって分けなくても大丈夫だったりはします。後半の Session では必須になりますが。
must の部分は見直し必須でお願いします！

2021-05-19 05:43 UTC, ykws commented on Yumemi-ios-training/Model/WeatherModel.swift
> +struct WeatherDataSource {
![badge](https://img.shields.io/badge/review-imo-orange.svg)

命名はファイル名の通り WeahterViewModel で良いと感じました。

xxxDataSource だと [UITableViewDataSource](https://developer.apple.com/documentation/uikit/uitableviewdatasource) protocol と同じような振る舞いを期待してしまうので。

CustomView に対して DataSource protocol を適合すると
次のようにやれなくもないですが、やり過ぎだと思うので参考程度に。

[CustomViewDataSourceExample](https://github.com/ykws/CustomDataSourceExample)

2021-05-19 05:43 UTC, ykws commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +        default:
![badge](https://img.shields.io/badge/review-must-red.svg)

rainy と default を一緒に扱うのは避けたいです。
現状、 sunny, cloudy, rainy と提示されている以外を受け取っても表示できてしまうのも、サーバ側の不具合を握り潰しているのでプロダクト全体のバグの温床になりやすくなってしまっています。

2021-05-19 05:43 UTC, ykws commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +    func reload() -> WeatherViewState? {
![badge](https://img.shields.io/badge/review-ask-blue.svg)

ここは Optional が返る可能性ありますか？

2021-05-19 05:43 UTC, ykws commented on Yumemi-ios-training/View/WeatherView.swift
> +    func changeDisplay(weatherViewState: WeatherViewState?) {
![badge](https://img.shields.io/badge/review-imo-orange.svg)

changeDisplay なので、 Optional の受け取りを拒否して良いと思いました。

2021-05-19 05:43 UTC, ykws commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +        let weatherString = weatherModel.reload()
![badge](https://img.shields.io/badge/review-imo-orange.svg)

Model を経由して取得するなら WeatherViewState を返して欲しいところですね。
ViewController からロジックを取り除いて Model 側にあるのが理想です。

2021-05-19 05:43 UTC, ykws commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +    let weatherModel: WeatherDataSource
![badge](https://img.shields.io/badge/review-nits-green.svg)

別でコメントしていますが、こういうところで命名にブレが出てきたら再考の余地があるかもと思って見直してみてください。

2021-05-19 05:43 UTC, ykws commented on Yumemi-ios-training/Model/WeatherViewState.swift
> +    var color: UIColor
![badge](https://img.shields.io/badge/review-must-red.svg)

可変ではないと思うので let で良いかと

2021-05-19 05:43 UTC, ykws commented on Yumemi-ios-training/Model/WeatherViewState.swift
> +    }
![badge](https://img.shields.io/badge/review-nits-green.svg)

property に対して set するだけなら initializer は省略可能です。

2021-05-19 05:45 UTC, el-hoshino requested changes

2021-05-19 05:45 UTC, el-hoshino commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +    private(set) var weatherView = WeatherView()
[nits]
`weatherView` を別に後から変更するわけではないので、`let` でも一応問題ないです；
もしくは本来VCの生成コストを軽減するために生成時にビューの生成をなるべく控えることもありますが、そんな時に使うのは `private(set) lazy var` です

2021-05-19 05:45 UTC, el-hoshino commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +    }
👍 
VCのライフサイクル的に、`loadView` で `self.view` を設定することをどこかで勉強したんですか？

2021-05-19 05:45 UTC, el-hoshino commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +    let weatherModel: WeatherDataSource
[nits]
まだSession2なので、責務の切り分けとかまだそこまで気にすることはないので、直接VC内で通信を組み込むのも現段階では特に問題ないですが、切り分けるなら、具象ではなく抽象に依存した方がテスト書きやすいのと、型名とプロパティ名を一致させた方が読みやすいです

2021-05-19 05:45 UTC, el-hoshino commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +    @objc func reloadButtonTapped() {
実はこれは `tapped` とかの状況説明のメソッド名よりも、普通に `reload` とかの命令のメソッド名の方がいいです；
参考： https://qiita.com/bitpoetics/items/a63bd1d9afc0b3221890

2021-05-19 05:45 UTC, el-hoshino commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +    func reload() -> WeatherViewState? {
[must]
一般的には、副作用がなく、戻り値を返すメソッドは「コマンド」ではなく「クエリ」です；Swift API Design Guidelines的には、クエリメソッドは動詞の原形ではなく、過去形や現在進行形、もしくはそもそも動詞ではなく名詞や形容詞などを使った方がいいです（関数型パラダイムのメソッドには一部例外ありますが）
参考： https://swift.org/documentation/api-design-guidelines/#strive-for-fluent-usage

2021-05-19 05:45 UTC, el-hoshino commented on Yumemi-ios-training/Model/WeatherModel.swift
> +    func reload() -> String  {
[must]
これも同じく、コマンドではなくクエリです

2021-05-19 05:45 UTC, el-hoshino commented on Yumemi-ios-training/Model/WeatherViewState.swift
> +    }
[nits]
structは自動的にmemberwise initializerが作られますので、自分で書かなくても大丈夫です

2021-05-19 06:17 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +    }
iOS設計パターン入門で勉強しました。ちょうど史さんのMVCのところですね。

2021-05-19 06:23 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +    func reload() -> WeatherViewState? {
ないですね。
これ以降のSessionでfetchWeathでエラーが返ってきた時にUIAlertVCとnilを返すのでつけていました。

2021-05-19 06:24 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +    private(set) var weatherView = WeatherView()
わかりました。

2021-05-19 06:25 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +    let weatherModel: WeatherDataSource
わかりました。

2021-05-19 06:26 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +        default:
わかりました。

2021-05-19 06:46 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +            return nil
@ykws 
これってdefaultでnil返す形が適切ですか？WeatherState型で返したいのですが、defaultを考慮するとオプショナルを加えざるをえなくなってしまうのですが、、、

2021-05-19 06:52 UTC, ykws commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +            return nil
@Hyperbolic4183 良いつまずきです！
default を扱いたくない時は [Enumerations](https://docs.swift.org/swift-book/LanguageGuide/Enumerations.html) の出番だと思うので、これを利用してデータを扱う方法にチャレンジしてみてください！

2021-05-19 06:56 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +            return nil
なるほど、enumはあるべくしてあるんですね。

2021-05-21 04:09 UTC, ruby109 commented on Yumemi-ios-training/View/WeatherView.swift
> +    var delegateAboutButton: WeatherDelegate?
ロジックを抽象に依存することを意識するは良いです。
でも、`Delegate Pattern`を使わない場合、Delegateのプロパティは必要ではないと思います。

2021-05-21 04:24 UTC, ruby109 commented on Yumemi-ios-training/Model/WeatherModel.swift
>          }
ここでは `return WeatherViewState(weather: weather)` で良いです

2021-05-21 04:44 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
>      }
@ykws 
列挙型Weatherを作成し、default でnilを返さなければならない問題を解決しました。
ただ、rawValueから返された値はオプショナル型なのでやむなく強制アンラップしていますが安全性などどうでしょうか？自分としてはここでのクラッシュの原因は一つに定まるので、良いと思っています。

2021-05-21 04:44 UTC, Hyperbolic4183 commented on Yumemi-ios-training/View/WeatherView.swift
> +    var delegateAboutButton: WeatherDelegate?
@el-hoshino

- WeatherViewControllerからロジックをWeatherModelへと移した
~~- プロトコルを作成し、抽象に依存するよう工夫した~~
- 関数名を`reload`->`reloading`に変更した

先日いただいたレビューを元に変更を加えました。レビューよろしくお願いします！

2021-05-21 04:47 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Model/WeatherModel.swift
>          }
@ruby109
レビューありがとうございます！
いただいた２つのレビューを反映させましたがどうでしょうか？

2021-05-21 04:54 UTC, ruby109 commented on Yumemi-ios-training/Model/WeatherModel.swift
>  }
``` swift
let weather = Weather(rawValue: weatherString)!
return WeatherViewState(weather: weather)
```
Swiftなら、このような書き方で大丈夫です

2021-05-21 05:05 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Model/WeatherModel.swift
>  }
@ruby109
知りませんでした！enumとswitchは相性いいですね。

2021-05-21 06:21 UTC, ykws commented on Yumemi-ios-training/Controller/WeatherViewController.swift
>      }
@Hyperbolic4183 `guard let weather` でエラー処理を追加するのが安全ですが、現段階では強制アンラップでクラッシュする可能性があることを認識していればこのままでも問題ないと思います。

2021-05-21 06:27 UTC, ykws commented on Yumemi-ios-training/Model/Weather.swift
> +    case rainy = "rainy"
![badge](https://img.shields.io/badge/review-nits-green.svg)

case と value が一致していたら省略可能です

```suggestion
    case sunny
    case cloudy
    case rainy
```

2021-05-21 06:31 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
>      }
@ykws
レビューありがとうございます！
`guard let `使う場合、 `else { return ○○}`で 何を返すことになりますか？
nilにした場合結局オプショナルをつけることになってしまい、WeatherViewState()にした場合はイニシャライズしないといけないと思いました。

2021-05-26 01:21 UTC, daichikuwa0618 approved these changes
先を見越した責務の分離もできていて、 MVC パターンに則った設計にもできていると思います。
DI もできているのも素晴らしいです。

個人的にはマージして問題ないと思います。

2021-05-26 01:21 UTC, daichikuwa0618 commented on Yumemi-ios-training/View/WeatherView.swift
> +        weatherImageView.image = UIImage(named: weatherViewState.weather.rawValue)?.withRenderingMode(.alwaysTemplate)
[FYI]
今回は大丈夫ですが、 `assets.xcassets` で `alwaysTemplate` の設定もできて、そこで実施した場合はコードで明示しなくても良くなります。

2021-05-26 01:21 UTC, daichikuwa0618 commented on Yumemi-ios-training/Model/WeatherModel.swift
> +    func reloading() -> WeatherViewState  {
[NITS]
`reload` でいいと思います。

2021-05-26 01:21 UTC, daichikuwa0618 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +//  ViewController.swift
[NITS]
`WeatherViewController.swift` ですかね。

2021-05-26 01:32 UTC, Hyperbolic4183 commented on Yumemi-ios-training/View/WeatherView.swift
> +        weatherImageView.image = UIImage(named: weatherViewState.weather.rawValue)?.withRenderingMode(.alwaysTemplate)
あ、そうなんですね。変更します。

2021-05-26 01:50 UTC, ykws approved these changes
![LGTM](https://image.lgtmoon.dev/97014)

2021-05-26 01:59 UTC, watanavex approved these changes
些細なところコメントしましたが、このままマージでも良いと思います。
っていうか、完成度が高杉くん
![LGTM](https://i.lgtm.fun/1f9k.png)

2021-05-26 01:59 UTC, watanavex commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +    }
[FYI]
アノテーションを付与すると、このイニシャライザを呼び出している箇所をコンパイルエラーで検知できます。
こんな感じ↓
`@available(*, unavailable, message: "init(coder:) has not been implemented")`

2021-05-26 01:59 UTC, watanavex commented on Yumemi-ios-training/Model/WeatherModel.swift
> +        let weather = Weather(rawValue: weatherString)!
[imo]
想定外の値でクラッシュさせる方針はアリだと思います！
その時、`fatalError` とかを使ってメッセージを出してあげると、
ログもわかりやすいし、コードの意図も伝わりやすいです。
(あえてやってるよ、という意図が伝わりますよね)
```Swift
guard let weather = Weather(rawValue: weatherString) else {
    fatalError("Unexpected xxx")
}

```

2021-05-26 02:02 UTC, watanavex commented on Yumemi-ios-training/View/WeatherView.swift
> +        weatherImageView.image = UIImage(named: weatherViewState.weather.rawValue)
[imo]
rawValueとリソース名を一致させる　っという暗黙のルールは、ウッカリミスで壊れやすいです。
それならば、文字列リテラルの方が私は好みです。
R.swiftなどのライブラリを用いるのがベストですが。
まぁ、それもおいおいで良いかと思います。

2021-05-26 02:10 UTC, ykws commented on Yumemi-ios-training/Controller/WeatherViewController.swift
>      }
@Hyperbolic4183 すみません！　コメント見落としていました！
やるなら下記のコメントのような感じが私も良いと思います！

https://github.com/Hyperbolic4183/YumemiWeather/pull/4#discussion_r639348396

2021-05-26 02:13 UTC, Hyperbolic4183 commented on Yumemi-ios-training/View/WeatherView.swift
> +        weatherImageView.image = UIImage(named: weatherViewState.weather.rawValue)
レビューありがとうございます！リソース名の扱いについては色々方法がありますよね。
R.swiftはよく聞くので触ってみようと思います。

2021-05-26 02:18 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
>      }
@ykws
いえいえ
クラッシュを回避したいことと何か返さなければいけないのでオプショナルを付与して長くなってしまうジレンマの解決方法がわかってよかったです。

2021-05-26 02:24 UTC, merged