Session3
Hyperbolic4183/YumemiWeather pull request #5
Opened 2021-05-26 05:23 UTC by Hyperbolic4183

## 行ったこと
- エラー時にアラートが表示されるようにした
## 工夫したところ
- if let を使って簡潔にエラー処理を記述した。

レビューよろしくお願いします！！

2021-05-26 07:54 UTC, ruby109 commented on Yumemi-ios-training/Model/WeatherModel.swift
>              return nil
Session 3のErrorのTypeはYumemiWeatherErrorなので、エラーやエラーメッセージをreturnした方がいいと思います
参考：
``` Swift
func reloading() -> Result<WeatherViewState, YumemiWeatherError> {
    do {
        let weatherString = try YumemiWeather.fetchWeather(at: "tokyo")
        guard let weather = Weather(rawValue: weatherString) else {
            fatalError("Weatherのイニシャライザに失敗")
        }
        return .success(WeatherViewState(weather: weather))
    } catch let error where error is YumemiWeatherError {
        return .failure(error as! YumemiWeatherError)
    } catch {
        //Session 3まで
        fatalError("想定外のエラーが発生しました")
    }
}
```
Refer：
https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html
https://qiita.com/koher/items/7e92414082476fb87b76

2021-05-26 07:56 UTC, ruby109 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +        }
ViewControllerの中でエラーメッセージも表示する
``` Swift
@objc func reload(_ sender: UIButton) {
        let result = weatherModel.reloading()
        switch result {
        case .success(let state):
            weatherView.changeDisplay(weatherViewState: state)
        case .failure(let error):
            let errorAlert = UIAlertController(title: "エラー", message: error.localizedDescription, preferredStyle: .alert)
            let errorAction = UIAlertAction(title: "OK", style: .default)
            errorAlert.addAction(errorAction)
            present(errorAlert, animated: true, completion: nil)
        }
    }
```

2021-05-26 08:14 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Model/WeatherModel.swift
>              return nil
レビューありがとうございます！
Resultを使うことで成功/失敗が明確になるんですね。

2021-05-26 08:31 UTC, el-hoshino commented on Yumemi-ios-training/Model/WeatherModel.swift
>              return nil
余談ですが、

```swift
catch let error where error is YumemiWeatherError
```

は

```swift
catch let error as YumemiWeatherError
```

でも書けますので、このほうが簡潔です 🙋

2021-05-26 08:33 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Model/WeatherModel.swift
>              return nil
ありがとうございます！

2021-05-26 08:49 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +        }
レビューありがとうございます！変更しました！

2021-05-27 03:27 UTC, ykws requested changes
他の方のレビュー指摘にすでに対応してもらっているので、概ね良い感じだと思います！
エラーメッセージの切り分けは課題の条件をまだ満たしていないと判断しましたので、改善をお願いします！

2021-05-27 03:27 UTC, ykws commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +            let errorAlert = UIAlertController(title: "エラー", message: error.localizedDescription, preferredStyle: .alert)
![must-badge](https://img.shields.io/badge/review-must-red.svg)

> エラーの内容に応じてメッセージを変更する

上記 Session3 の課題の意図は、 `YumemiWeatherError` に応じて切り替えて欲しいです。

```swift
public enum YumemiWeatherError: Swift.Error {
    case invalidParameterError
    case unknownError
}
```

https://github.com/yumemi-inc/ios-training/blob/f0d6b45d5154f9a7e42f43782b38f369bbeb2892/Sources/YumemiWeather/YumemiWeather.swift#L21

Session3 では `unknownError` しか返らないのですが、エラーの IF に基づいて実装することで、次の Session の変更で別の API を呼び出しに変わっても強固な実装になります。

またエラーメッセージの表示に関して、

> メッセージの内容は自由です

とありますが、現状のようにシステムエラーをそのまま表示するのは、 UI 層としては不適切になります。

<img alt="Simulator Screen Shot - iPod touch (7th generation) - 2021-05-27 at 12 07 16" src="https://user-images.githubusercontent.com/5770480/119760662-59e68580-bee5-11eb-884c-e307cbb068ec.png" width="280">

まとめると、
`YumemiWeatherError` に応じてユーザフレンドリーなエラーメッセージを表示するようにしてみてください。

2021-05-28 00:28 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +            let errorAlert = UIAlertController(title: "エラー", message: error.localizedDescription, preferredStyle: .alert)
@ykws
レビューありがとうございます！
頂いたレビューを反映しました。switchのネストが気になるところですが、許容範囲と自分は感じたのでそのままにしました。コーディング規則等あれば教えていただきたいです。

2021-05-28 00:58 UTC, ykws commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +            let errorAlert = UIAlertController(title: "エラー", message: error.localizedDescription, preferredStyle: .alert)
@Hyperbolic4183 良い感覚だと思います！

このままでも許容範囲だと私も思いますが、

YumemiWeatherError は API 側の表現なので、 WeatherApp 側の Model として表現できないか試してみてください。
現状は Controller が API に依存していますが、 WeatherApp の Model に依存するように変更して、 Controller が API の変更に影響を受けないようにするのがより良いです。 
結果的にネストも浅くできます。

この研修でのコーディング規則はないと思います。
自身で制定してもらってそれに従うのもありです！

2021-05-28 01:23 UTC, Hyperbolic4183 commented
@ykws 
これでどうでしょう？？もっとスマートなやり方があるかもしれませんが。。
`reloading()`の返り値をResultだけでなくStringも付けられればベストなのですが、weatherModelにプロパティを作ることにしました。

2021-05-28 07:20 UTC, daichikuwa0618 requested changes
一点だけ修正お願いします！
[FYI] はただの情報提供なので、このままで大丈夫です。

2021-05-28 07:20 UTC, daichikuwa0618 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +        var message = ""
[NITS]
この `message` は一つ狭いスコープ (`.failure` のスコープ) に移動できるので、そっちで抑えましょう！

ちなみに、今のままだとなんのメッセージかな？ってなりますが、 `.failure` のスコープに移すとエラーメッセージだろうなと文脈が確定するメリットもあります！

2021-05-28 07:20 UTC, daichikuwa0618 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +        let result = weatherModel.reloading()
[FYI] (For Your Information)
`Result` は `switch` で分岐させるのが一般的ですが、実は `let result = try weatherModel.reloading().get()` とすることで do-catch によるハンドリングもできちゃいます！

2021-05-28 07:25 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +        let result = weatherModel.reloading()
そうなんですね！もしかしてResultに対してはdo catchの方がよく見るコードだったりします？

2021-05-28 07:29 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +        let result = weatherModel.reloading()
2択なのでdo catchの方が見やすそうですよね

2021-05-28 07:36 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +        var message = ""
レビューありがとうございます！
反映させました！

2021-05-28 07:37 UTC, daichikuwa0618 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +        let result = weatherModel.reloading()
うーーん、ほとんど `get()` して do-catch してるのは見たことないですね。。。

多分ですが、そこまで知られてってのが最もな理由だと思います。

2021-05-28 07:38 UTC, daichikuwa0618 approved these changes
マージして問題ないと思います！

2021-05-28 07:40 UTC, merged