Session4
Hyperbolic4183/YumemiWeather pull request #6
Opened 2021-05-28 08:32 UTC by Hyperbolic4183

## 行ったこと
fetchWeatherからjsonを取得し、その情報をラベルに反映させた。

## 懸念点
- WeatherModel.swift　のdo {}内にtryが二つあり、異なるエラーが一つのcatchに飛ぶこと
- WeatherModel.swift force castばかり

2021-05-28 09:58 UTC, daichikuwa0618 requested changes
パット見て気になったところをレビューしました。

2021-05-28 09:58 UTC, daichikuwa0618 commented on Yumemi-ios-training.xcodeproj/project.pbxproj
> +				D9DA6EE12654DCB800E80C3E /* WeatherData.swift */,
[MUST]
おっとコンフリクトしてますね。
rebase した名残ですかね？

ちょっと面倒ですが直してみてください。

2021-05-28 09:58 UTC, daichikuwa0618 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +        present(errorAlert, animated: true, completion: nil)
[NITS]
このインデントは修正前で良い気がします。

2021-05-28 09:58 UTC, daichikuwa0618 commented on Yumemi-ios-training/Model/WeatherData.swift
> +    let max_temp: Int
[MUST]
Swift は camelCase が基本です。

https://swift.org/documentation/api-design-guidelines/
> Follow case conventions. Names of types and protocols are UpperCamelCase. Everything else is lowerCamelCase.

2021-05-28 09:58 UTC, daichikuwa0618 commented on Yumemi-ios-training/Model/WeatherModel.swift
> +            let highestTemperature = weatherDictionary["max_temp"] as! Int
[IMO]
懸念点にかかれていましたが、 force cast も悪くないと思います。
また、クラッシュさせて気付けるという意味では `assertionFailure` も選択肢になると思います。

ただ、自分だったらここは外部 API 依存であり、いつ何時 Key が変わるか分からないので Optional で扱います。
そして、期待する Key が無ければ `.failure` を return してエラーを通知します。

2021-05-28 09:58 UTC, daichikuwa0618 commented on Yumemi-ios-training/WeatherModel.swift
> +struct WeatherModel {
[MUST]
これ多分 rebase で解決し忘れた過去の `WeatherModel` ですよね。

2021-05-28 09:58 UTC, daichikuwa0618 commented on Yumemi-ios-training/WeatherViewController.swift
> +class WeatherViewController: UIViewController {
[MUST]
これも rebase の残骸かと。

2021-05-31 03:48 UTC, ruby109 commented on Yumemi-ios-training/Model/WeatherModel.swift
> +            let weatherDictionary = try JSONSerialization.jsonObject(with: weatherData) as! Dictionary<String, Any>
[IMO]
ここは二つのErrorがあるので、も一つの `catch let error as NSError` を加えて、新しの`YumemiAppError`(e.g. `.jsonMappingError`)を返しての方かいいと思います。

2021-06-02 00:43 UTC, Hyperbolic4183 commented on Yumemi-ios-training.xcodeproj/project.pbxproj
> +				D9DA6EE12654DCB800E80C3E /* WeatherData.swift */,
@daichikuwa0618
レビューありがとうございます！
rebaseしたときにSession3とSession4のファイルの存在の差分でコンフリクト起きたんですよね。
競合メッセージをコメントアウトしたらxcode開けるようになったので、解決できたのかなと思ってました。
直すというのは、pbxprojファイルがどういった状態になることを指しますか？

2021-06-02 03:30 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Model/WeatherModel.swift
> +            let weatherDictionary = try JSONSerialization.jsonObject(with: weatherData) as! Dictionary<String, Any>
@ ruby109
レビューありがとうございます！
頂いたレビューを反映させたのですがどうでしょうか？

2021-06-02 03:47 UTC, daichikuwa0618 requested changes
一点直ってなかったので修正お願いします。

2021-06-02 03:47 UTC, daichikuwa0618 commented on Yumemi-ios-training/Model/WeatherData.swift
> +    let max_temp: Int
ここ直ってないです〜

2021-06-02 03:47 UTC, daichikuwa0618 commented on Yumemi-ios-training/Model/WeatherModel.swift
> +            weatherDataString = try YumemiWeather.fetchWeather("{\"area\": \"tokyo\", \"date\": \"2020-04-01T12:00:00+09:00\" }")
[ASK]
ここで取得した `weatherDataString` を使って `do {}` スコープ外で `weatherDictionary` を作ってるのは do-catch がネストするのが嫌だった感じですかね？？

2021-06-02 03:47 UTC, daichikuwa0618 commented on Yumemi-ios-training/Model/WeatherModel.swift
> +        let highestTemperature = weatherDictionary!["max_temp"] as! Int
[IMO]
Json のマッピング処理は関数に切り出したほうが良いかもです。
これは再利用性を高めるというよりは、可読性のためですね。

2021-06-02 06:48 UTC, Hyperbolic4183 commented
頂いたレビューを反映させました。
レビューよろしくお願いします。

2021-06-02 08:21 UTC, Hyperbolic4183 commented
モデルで行っていたweatherViewStateをコントローラーで行うように設計を見直した。モデルクラスはあくまで外部パッケージとの関係を担うだけになっている。

2021-06-03 15:45 UTC, ykws commented on Yumemi-ios-training/Model/WeatherData.swift
> +    let max_temp: Int
Xcode 上から削除されているけど、リポジトリに残ってしまっているようなので、不要ならファイルごと削除してコミットすれば良いと思います。

2021-06-04 00:24 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Model/WeatherData.swift
> +    let max_temp: Int
レビューありがとうございます！
消しました！

2021-06-04 02:28 UTC, daichikuwa0618 reviewed
かなり責務を意識されているのが伝わります。
少し細かい tips を書いたので見てください。

2021-06-04 02:28 UTC, daichikuwa0618 commented on Yumemi-ios-training/Model/WeatherModel.swift
> +    func jsonMappedDictionary(weatherData: Data) -> [String: Any] {
`jsonMappedDictionary(weatherData:)` だと何をする関数か分からないと感じました。

[Swift API Guidlines](https://swift.org/documentation/api-design-guidelines/) には

> Prefer method and function names that make use sites form grammatical English phrases.

とあって、なんとなくつなげて読んだときに意味のあるような文章になるように考えると命名しやすいかもしれません。

例えばここだと、「`Data` から `Dictionary` に変換する」ということをやっているので、

```swift
func convert(from weatherData: Data) -> [String: Any]
```

とかでしょうか。
仮引数名で `Data` 型からという情報があって、返り値の型で `Dictionary` への変換であることがわかるので、自分だったらこんな感じで命名します。

これだと使うときに `convert(from: weatherData)` ってなって、英語としても自然な流れですよね。

2021-06-04 02:28 UTC, daichikuwa0618 commented on Yumemi-ios-training/Model/WeatherModel.swift
> +            return weatherDictionary!
[ASK]
Force unwrapping しているのは、 [String: Any] へのダウンキャストになっており、 Json であれば必ず成功するからという理解であってますか？

2021-06-04 02:28 UTC, daichikuwa0618 commented on Yumemi-ios-training/Model/WeatherModel.swift
> +            fatalError("JSONSerializationに失敗しました")
もしかすると、返り値をオプショナルにして、 catch では `assertionFailure` でデバッグ時だけ落とし、 nil を返す方が良いかも知れないです。
`try` が失敗しないはずと思っているのであれば、 `try!` にすることで do-catch が要らなくなるか、丁寧にハンドリングしても `fatalError` の message は「JSONSerialization には失敗しないはず」とかのほうが、実装時の気持ちをのこしておけて、修正する時の目印になります。

"JSONSerializationに失敗しました" では事実しか述べられてないので、ここに来たときに原因の仮設を立てるところからになってしまいますが、JSONSerialization には失敗しないはず" ってなってたらなんで実装の時に失敗しないと思い込んでいたかというところを紐解くことで少し早く原因に辿り着けそうです。

2021-06-04 02:28 UTC, daichikuwa0618 commented on Yumemi-ios-training/Model/WeatherModel.swift
> +            let weatherData = weatherDataString.data(using: String.Encoding.utf8)!
[FYI]
実は
```swift
let weatherData = Data(weatherDataString.utf8)
```
ってかけばオプショナル考えなくて良くなります。

ただ、[[Swift] string.data(using: .utf8)ってnilになるの？](https://qiita.com/YOCKOW/items/530b95cfbcb22eac22f2) にある通り、この方法でも絶対に nil にならないので force unwrapping でもいいです。

2021-06-04 02:42 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Model/WeatherModel.swift
> +    func jsonMappedDictionary(weatherData: Data) -> [String: Any] {
なるほど、前置詞を引数ラベルにすると読みやすくなりますね

2021-06-04 02:44 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Model/WeatherModel.swift
> +            return weatherDictionary!
そうです。
```
let weatherDictionary = try JSONSerialization.jsonObject(with: weatherData) as! [String: Any]            return weatherDictionary
```
の方がよかったですかね。

2021-06-04 03:06 UTC, daichikuwa0618 commented on Yumemi-ios-training/Model/WeatherModel.swift
> +            return weatherDictionary!
それでも同じなので、どちらでも大丈夫です。

2021-06-04 04:05 UTC, rizumita requested changes

2021-06-04 04:05 UTC, rizumita commented on Yumemi-ios-training/Controller/WeatherViewController.swift
>      @objc func reload(_ sender: UIButton) {
本メソッドでDictionary→Weather→WeatherViewStateという変換を行っていますが、WeatherまではModelレイヤーの存在なのでWeatherModel.reloadingからWeatherが返ってくる方が自然に思います。

エラーからのUIAlertControllerの生成も別の場所に移動すると本メソッドの見通しがよくなります。

また、値の変換として考えると

```swift
let result = weatherModel.reloading().map { WeatherViewState(weather: $0, …) }
```

と書くようにもできます。

2021-06-04 04:05 UTC, rizumita commented on Yumemi-ios-training/Model/WeatherModel.swift
> +    func reloading() -> Result<[String: Any], WeatherAppError> {
reloadするメソッド名にingをつけるのは不適切です。

2021-06-04 04:05 UTC, rizumita commented on Yumemi-ios-training/Model/WeatherModel.swift
>  struct WeatherModel {
WeatherModelとWeatherが存在していて分かりにくくなっています。
WeatherModelの名前を責務を表したものにすると良いと思います。

2021-06-04 04:05 UTC, rizumita commented on Yumemi-ios-training/Controller/WeatherViewState.swift
> +    let lowestTemperature: Int
Intとして保持していますが、表示に用いるのはStringなので状態としてはStringで保持するのが適切に思います。

2021-06-04 04:05 UTC, rizumita commented on Yumemi-ios-training/Controller/WeatherViewState.swift
>      let weather: Weather
Weatherを保持していますが、Viewの状態はImageということであればImageで保持すると良いです。

2021-06-04 05:58 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Model/WeatherModel.swift
>  struct WeatherModel {
APIとの連携を行う唯一のクラスなので、WeatherGateWayに変更しました。

2021-06-04 06:00 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Model/WeatherModel.swift
> +    func reloading() -> Result<[String: Any], WeatherAppError> {
@rizumita
fetchWeatherにしました。
APIと同じメソッド名になっていますが、そういったことを避けることは推奨されていますか？

2021-06-04 06:21 UTC, rizumita commented on Yumemi-ios-training/Model/WeatherModel.swift
> +    func reloading() -> Result<[String: Any], WeatherAppError> {
YumemiWeatherのとらえ方に関わってきます。
YumemiWeatherがAPIアクセスのための別レイヤーの型であれば同じメソッド名のこともあると思います。
YumemiWeatherがモデルレイヤーでYumemiWeatherGateWayと同じレイヤーとするなら、fetchWeatherという名前が表す責務が二つの型に存在していて、設計が不適切な可能性が高いです。

2021-06-04 06:26 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Model/WeatherModel.swift
> +    func reloading() -> Result<[String: Any], WeatherAppError> {
なるほど。PackageManagerをモデルと同レイヤーとして捉えようと思います。
fetchYumemiWeatherにします。

2021-06-04 06:33 UTC, novr commented on Yumemi-ios-training/Model/WeatherModel.swift
>  struct WeatherModel {
[IMO] fetchするModelなので〜Fetcherでもよいかと

2021-06-04 06:34 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Model/WeatherModel.swift
>  struct WeatherModel {
ありがとうございます！そうします！

2021-06-04 06:56 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
>      @objc func reload(_ sender: UIButton) {
@rizumita
WeatherViewStateの値の生成のためにはDictionaryが必要なので、返り値をWeatherに変えることは難しいと思いました。
別レイヤーのクラス/構造体を使うことはどこかで許容しないといけないと思うのですが、何か解決策はありますか？

2021-06-04 07:05 UTC, rizumita commented on Yumemi-ios-training/Controller/WeatherViewController.swift
>      @objc func reload(_ sender: UIButton) {
@Hyperbolic4183 Wheatherが必要な情報を持っていないので追加情報としてDictionaryが必要になっているように見えます。

2021-06-04 09:18 UTC, Hyperbolic4183 commented on Yumemi-ios-training/Controller/WeatherViewController.swift
>      @objc func reload(_ sender: UIButton) {
@rizumita
Weather列挙型であったものをプロパティに持ったWeatherInformation構造体を作成し解決を図ったのですがどうでしょうか？

2021-06-09 04:03 UTC, novr requested changes

2021-06-09 04:03 UTC, novr commented on Yumemi-ios-training/Model/Fetcher.swift
> +            let weatherDictionary = convert(from: weatherData)!
[MUST] convertが失敗時にnilを返すが!になっている
convertではassertionFailureになっているが、ここで実行時エラーが発生してしまい、convertの失敗がハンドリングできません

2021-06-09 04:03 UTC, novr commented on Yumemi-ios-training/Controller/WeatherViewController.swift
> +            guard let lowestTemperature = information.weatherDictionary!["min_temp"] as? Int,
[IMO] YumemiWeatherのweatherは隠蔽されているが、min_tempとmax_tempの依存がView側に来てしまっています

2021-06-11 03:58 UTC, daichikuwa0618 approved these changes
細かい点指摘しましたがほとんどできてそうなので Approve します！

2021-06-11 03:58 UTC, daichikuwa0618 commented on Yumemi-ios-training/Model/Fetcher.swift
> +            fatalError("想定外のエラーが発生しました")
`YumemiWeather` パッケージがアップデート等で急に `YumemiWeatherError` 以外のエラーを返すことも考えられるので、ここは `assertionFailure` にして `.failure(.unknown)` とかを返してやるのがいいと思います。

2021-06-11 03:58 UTC, daichikuwa0618 commented on Yumemi-ios-training/Model/WeatherInformation.swift
> +    init(_ weather: Weather, _ minTemperature: String, _ maxTemperature: String) {
[IMO]
全部の仮引数名を省略するとちょっと可読性が落ちる気がします。
ここは `struct` のイニシャライズですし仮引数を無くしても違和感はないかと。

2021-06-11 03:58 UTC, daichikuwa0618 commented on Yumemi-ios-training/Model/Fetcher.swift
> +            }
[NITS]
ちょっとつめつめになってるので、 catch の前や処理のまとまりで空行入れたほうがいいかもです。

2021-06-11 04:38 UTC, novr approved these changes
![LGTM](https://image.lgtmoon.dev/84308)

2021-06-11 05:11 UTC, merged